### ISSUE TITLE
feat: milk bottling supply chain rework

### ISSUE THREAD

**Issue by bahrmichael** [bahrmichael/factorio-tycoon#58]
Requires https://github.com/bahrmichael/factorio-tycoon/issues/56

- [x] Milk is now a fluid (from https://github.com/bahrmichael/factorio-tycoon/issues/57)
- [x] Player can craft bottles (from https://github.com/bahrmichael/factorio-tycoon/issues/57)
- [x] Player can refurbish bottles (from https://github.com/bahrmichael/factorio-tycoon/issues/57)

---

This story is automatically done when #56 and #57 are done.
