### ISSUE TITLE
feat: bread supply chain

### ISSUE THREAD

**Issue by bahrmichael** [bahrmichael/factorio-tycoon#60]
Requires https://github.com/bahrmichael/factorio-tycoon/issues/57

- [x] Milk is now a fluid: #57 
- [x] Player can craft flour: https://github.com/bahrmichael/factorio-tycoon/issues/56
- [x] Player can craft dough: https://github.com/bahrmichael/factorio-tycoon/issues/56
- [x] Furnaces can craft bread: https://github.com/bahrmichael/factorio-tycoon/issues/56

---

This story is automatically done when https://github.com/bahrmichael/factorio-tycoon/issues/56 and https://github.com/bahrmichael/factorio-tycoon/issues/57 are done.
